<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SingamDB.Query</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SingamDB.Core\SingamDB.Core.csproj" />
    <ProjectReference Include="..\SingamDB.Storage\SingamDB.Storage.csproj" />
    <ProjectReference Include="..\SingamDB.Indexing\SingamDB.Indexing.csproj" />
  </ItemGroup>

</Project>
