<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SingamDB.Core\SingamDB.Core.csproj" />
    <ProjectReference Include="..\SingamDB.Storage\SingamDB.Storage.csproj" />
    <ProjectReference Include="..\SingamDB.Indexing\SingamDB.Indexing.csproj" />
    <ProjectReference Include="..\SingamDB.Query\SingamDB.Query.csproj" />
    <ProjectReference Include="..\SingamDB.Network\SingamDB.Network.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SingamDB.Server</RootNamespace>
  </PropertyGroup>

</Project>
